//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klyte.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Klyte.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allow to write text in-game to simulate stuff like boards or signs..
        /// </summary>
        internal static string root_modDescription {
            get {
                return ResourceManager.GetString("root_modDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_FOLDERSRC_ASSET.
        /// </summary>
        internal static string WTS_FOLDERSRC_ASSET {
            get {
                return ResourceManager.GetString("WTS_FOLDERSRC_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_FOLDERSRC_LOCAL.
        /// </summary>
        internal static string WTS_FOLDERSRC_LOCAL {
            get {
                return ResourceManager.GetString("WTS_FOLDERSRC_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_IMAGESRC_ASSET.
        /// </summary>
        internal static string WTS_IMAGESRC_ASSET {
            get {
                return ResourceManager.GetString("WTS_IMAGESRC_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_IMAGESRC_LOCAL.
        /// </summary>
        internal static string WTS_IMAGESRC_LOCAL {
            get {
                return ResourceManager.GetString("WTS_IMAGESRC_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_PARAMTYPE_PLAINTEXT.
        /// </summary>
        internal static string WTS_PARAMTYPE_PLAINTEXT {
            get {
                return ResourceManager.GetString("WTS_PARAMTYPE_PLAINTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_PARAMTYPE_VARIABLE.
        /// </summary>
        internal static string WTS_PARAMTYPE_VARIABLE {
            get {
                return ResourceManager.GetString("WTS_PARAMTYPE_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WTS_PICK_A_SEGMENT.
        /// </summary>
        internal static string WTS_PICK_A_SEGMENT {
            get {
                return ResourceManager.GetString("WTS_PICK_A_SEGMENT", resourceCulture);
            }
        }
    }
}
